secretGenerator:
- name: mysql-root-passwd
  literals:
  - root-passwd=P@ssw0rd
- name: mysql-user-passwd
  literals:
  - user-passwd=password
configMapGenerator:
- name: mysql-db-name
  literals:
  - db-name=login
- name: mysql-user
  literals:
  - user=dbadmin
- name: initdb
  files:
  - user.sql
resources:
  - statefulset-mysql.yaml
  - service-mysql.yaml
  - deployment-phpmyadmin.yaml
  - service-phpmyadmin.yaml
  - deployment-login.yaml
  - service-login.yaml
 # - pod-testdb.yaml
