apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/name: grafana
    pod-template-hash: 55dbdfd8cf
  name: loki-grafana-55dbdfd8cf-frff7
  namespace: loki
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/name: grafana
    pod-template-hash: 55dbdfd8cf
  type: NodePort
status:
  loadBalancer: {}
