apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin
    app-tier: frontend
    zone: public
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: phpmyadmin
        app-tier: frontend
        zone: public
    spec:
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
        env:
        - name: PMA_HOST
          value: mysql-h
        resources: {}
status: {}
