apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-phpmyadmin
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: phpmyadmin
      port:
        number: 80
