secretGenerator:
- name: mysql-root-passwd
  literals:
  - root-passwd=P@ssw0rd
- name: mysql-user-passwd
  literals:
  - user-passwd=P@ssw0rd
configMapGenerator:
- name: mysql-db-name
  literals:
  - db-name=tuxtum
- name: mysql-user
  literals:
  - user=dbadmin
- name: initdb
  files:
  - demo.sql
resources:
  - statefulset-mysql.yaml
  - service-mysql.yaml
  - deployment-phpmyadmin.yaml
  - service-phpmyadmin.yaml
  - pod-testdb.yaml
