apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nodeport-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
  type: NodePort
status:
  loadBalancer: {}
