---
 - name: Disable disable
   hosts: all
   tasks:

   - name: sysctl disable ipv6
     sysctl:
       name: "{{ item }}"
       state: present
       value: 1
       sysctl_file: /etc/sysctl.conf
       reload: yes
     loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6
        - net.ipv6.conf.ens160.disable_ipv6