---
  - name: Setup Docker on Ubuntu 18.04
    hosts: docker
    tasks:
    - name: apt update & apt upgrade
      apt:
        update_cache: yes
        upgrade: dist
    - name: apt dependency docker package
      apt:
        name: "{{ package }}"
        state: present
      vars:
        package:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
    - name: Add Docker's Official GPG Key;
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install Docker engine
      apt:
        name: "{{ package }}"
        state: present
      vars:
        package:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Docker service enable
      systemd:
        state: started
        name: docker
        enabled: yes