---
 - name: Prerequisite
   hosts: k8s-cluster
   tasks:

   - name: sysctl disable ipv6
     sysctl:
       name: "{{ item }}"
#       state: present
       value: 1
       sysctl_file: /etc/sysctl.d/k8s.conf
       reload: yes
     loop:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        
      
      