apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: demo
secretGenerator:
- name: mysql-root-passwd
  literals:
  - root-passwd=P@ssw0rd
- name: mysql-user-passwd
  literals:
  - user-passwd=password
configMapGenerator:
- name: mysql-db-name
  literals:
  - db-name=employee
- name: mysql-user
  literals:
  - user=dbadmin
- name: initdb
  files:
  - employee.sql
resources:
  - react-deployment.yaml
  - nodejs-deployment.yaml
  - statefulset-mysql.yaml
  - service.yaml
 # - pod-testdb.yaml
