apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      containers:
      - image: gambitmis/mern-demo:backend
        imagePullPolicy: Always
        name: mern-demo
        ports:
        - containerPort: 3001
        resources: {}
status: {}
