apiVersion: v1
kind: Service
metadata:
  name: mern-react
spec:
  type: NodePort
  selector:
    app: react
  ports:
    - port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mern-nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30080
