apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-mern
spec:
  selector:
    matchLabels:
      app: mysql-mern
  serviceName: "mysql-mern"
  #replicas: 3
  template:
    metadata:
      labels:
        app: mysql-mern
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: db
          mountPath: /var/lib/mysql
        - name: config-initdb
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-passwd
              key: root-passwd
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-db-name
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-user
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-passwd
              key: user-passwd
      volumes:
        - name: config-initdb
          configMap:
            name: initdb
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-mern
  clusterIP: None
